### ISSUE TITLE
Verbose=True is not effect in readdali.py

### ISSUE THREAD

**Issue by jinguman** [crotwell/simple-dali#1]
I changed the verbose=True in "readdali.py", but there is no log print.
In debug mode, It still shows verbose=False.

So I check the "websocketdali.py", and changed the code.

line 8:
[before] super(WebSocketDataLink, self).__init__(verbose)
[after] super(WebSocketDataLink, self).__init__(verbose=verbose)

After that, it works.
Please, fix the code.

**Comment by crotwell** [comment]
Thanks for bug report, fixed in 5ac164d4aeac8f73c0dbbefdd414a04b7ed879a1
